
################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= convolutionTexture
# CUDA source files (compiled with cudacc)
CUFILES		:= convolutionTexture.cu
# CUDA dependency files
CU_DEPS		:= convolutionTexture_kernel.cu
# C/C++ source files (compiled with gcc / c++)
# CCFILES		:= convolution_gold.cpp


################################################################################
# Rules and targets

include common.mk
